---

apiVersion: v1
kind: Service
metadata:
 name: kuma-svc-local
 namespace: monitoring
spec:
 type: NodePort
 selector:
   app: uptimekuma-d
 ports:
   - port: 3001
     targetPort: 3001
     nodePort: 32122

